#!/bin/bash
# CallingClaw 2.0 — One-Click Setup Script
# Run: chmod +x setup.sh && ./setup.sh

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo ""
echo "   ██████╗ █████╗ ██╗     ██╗     ██╗███╗   ██╗ ██████╗  ██████╗██╗      █████╗ ██╗    ██╗"
echo "  ██╔════╝██╔══██╗██║     ██║     ██║████╗  ██║██╔════╝ ██╔════╝██║     ██╔══██╗██║    ██║"
echo "  ██║     ███████║██║     ██║     ██║██╔██╗ ██║██║  ███╗██║     ██║     ███████║██║ █╗ ██║"
echo "  ██║     ██╔══██║██║     ██║     ██║██║╚██╗██║██║   ██║██║     ██║     ██╔══██║██║███╗██║"
echo "  ╚██████╗██║  ██║███████╗███████╗██║██║ ╚████║╚██████╔╝╚██████╗███████╗██║  ██║╚███╔███╔╝"
echo "   ╚═════╝╚═╝  ╚═╝╚══════╝╚══════╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═════╝╚══════╝╚═╝  ╚═╝ ╚══╝╚══╝"
echo "                            Setup Script v2.0"
echo ""

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

ok()   { echo -e "  ${GREEN}✓${NC} $1"; }
warn() { echo -e "  ${YELLOW}!${NC} $1"; }
fail() { echo -e "  ${RED}✗${NC} $1"; }
info() { echo -e "  ${BLUE}→${NC} $1"; }

# ── Step 1: Check Prerequisites ──────────────────────────────────

echo -e "\n${BLUE}[1/7]${NC} Checking prerequisites...\n"

# Check macOS
if [[ "$(uname)" != "Darwin" ]]; then
  fail "CallingClaw requires macOS (detected: $(uname))"
  exit 1
fi
ok "macOS detected ($(sw_vers -productVersion))"

# Check Homebrew
if ! command -v brew &>/dev/null; then
  warn "Homebrew not found — installing..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
ok "Homebrew $(brew --version | head -1 | awk '{print $2}')"

# Check Bun
if ! command -v bun &>/dev/null; then
  warn "Bun not found — installing..."
  curl -fsSL https://bun.sh/install | bash
  export PATH="$HOME/.bun/bin:$PATH"
fi
ok "Bun $(bun --version)"

# Check Python 3
PYTHON_BIN=""
for candidate in python3 /opt/miniconda3/bin/python3 /usr/local/bin/python3 /opt/homebrew/bin/python3; do
  if command -v "$candidate" &>/dev/null; then
    PYTHON_BIN="$candidate"
    break
  fi
done

if [[ -z "$PYTHON_BIN" ]]; then
  warn "Python 3 not found — installing via Homebrew..."
  brew install python@3.11
  PYTHON_BIN="python3"
fi
ok "Python $($PYTHON_BIN --version 2>&1 | awk '{print $2}') at $PYTHON_BIN"

# Check Google Chrome
if [[ -d "/Applications/Google Chrome.app" ]]; then
  ok "Google Chrome installed"
else
  warn "Google Chrome not found — CallingClaw needs it to join Google Meet"
  info "Install from: https://www.google.com/chrome/"
fi

# ── Step 2: Audio Setup (BlackHole no longer required) ───────────
# BlackHole virtual audio was removed in v2.7.12 — audio injection
# now uses Playwright addInitScript for browser-level audio routing.

echo -e "\n${BLUE}[2/7]${NC} Audio setup...\n"
ok "Audio injection via Playwright (no virtual audio driver needed)"

# ── Step 3: Install Dependencies ─────────────────────────────────

echo -e "\n${BLUE}[3/7]${NC} Installing dependencies...\n"

info "Installing Bun packages..."
bun install --silent
ok "Bun dependencies installed"

info "Installing Python packages..."
$PYTHON_BIN -m pip install -q -r python_sidecar/requirements.txt 2>/dev/null
ok "Python dependencies installed"

# ── Step 4: Setup .env File ──────────────────────────────────────

echo -e "\n${BLUE}[4/7]${NC} Configuring environment...\n"

ENV_FILE="$SCRIPT_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
  ok ".env file already exists"
  info "To reconfigure, edit: $ENV_FILE"
else
  echo ""
  echo -e "  ${YELLOW}API Keys Configuration${NC}"
  echo "  (Press Enter to skip any key — you can set them later in the web panel)"
  echo ""

  read -p "  OpenAI API Key (required for voice): " OPENAI_KEY
  read -p "  OpenRouter API Key (for Computer Use): " OPENROUTER_KEY
  read -p "  Anthropic API Key (optional, alt CU): " ANTHROPIC_KEY

  cat > "$ENV_FILE" << EOF
# CallingClaw 2.0 Environment Configuration
# Generated by setup.sh on $(date)

# OpenAI — Required for voice (Realtime API)
OPENAI_API_KEY=${OPENAI_KEY}

# OpenRouter — Recommended for Computer Use (Claude gateway)
OPENROUTER_API_KEY=${OPENROUTER_KEY}

# Anthropic — Optional (direct Claude API, alternative to OpenRouter)
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}

# Google Calendar — Set via web panel or manually
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
# GOOGLE_REFRESH_TOKEN=

# Python path (auto-detected)
PYTHON_PATH=${PYTHON_BIN}

# Screen resolution of this machine
SCREEN_WIDTH=1920
SCREEN_HEIGHT=1080
EOF

  ok ".env file created"
fi

# ── Step 5: macOS Permissions ────────────────────────────────────

echo -e "\n${BLUE}[5/7]${NC} macOS permissions setup...\n"

info "CallingClaw needs these macOS permissions to function:"
echo ""
echo "    1. Screen Recording  — for screenshots & Computer Use"
echo "    2. Accessibility     — for mouse/keyboard automation (PyAutoGUI)"
echo "    3. Microphone        — for audio capture (BlackHole routing)"
echo ""

# Detect the terminal app
TERMINAL_APP="Terminal"
if [[ "$TERM_PROGRAM" == "iTerm.app" ]]; then
  TERMINAL_APP="iTerm2"
elif [[ "$TERM_PROGRAM" == "vscode" ]]; then
  TERMINAL_APP="Visual Studio Code"
elif [[ "$TERM_PROGRAM" == "WarpTerminal" ]]; then
  TERMINAL_APP="Warp"
fi

info "Your terminal ($TERMINAL_APP) needs these permissions."
echo ""

read -p "  Open System Settings to grant permissions? [Y/n] " OPEN_SETTINGS

if [[ "$OPEN_SETTINGS" != "n" ]] && [[ "$OPEN_SETTINGS" != "N" ]]; then
  # Screen Recording
  info "Opening Screen Recording settings..."
  open "x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture" 2>/dev/null || \
    open -b com.apple.systempreferences /System/Library/PreferencePanes/Security.prefPane 2>/dev/null || true
  echo -e "    ${YELLOW}→ Add '$TERMINAL_APP' and 'Python' to the list, then toggle ON${NC}"
  read -p "    Press Enter when done..."

  # Accessibility
  info "Opening Accessibility settings..."
  open "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility" 2>/dev/null || true
  echo -e "    ${YELLOW}→ Add '$TERMINAL_APP' and 'Python' to the list, then toggle ON${NC}"
  read -p "    Press Enter when done..."

  # Microphone
  info "Opening Microphone settings..."
  open "x-apple.systempreferences:com.apple.preference.security?Privacy_Microphone" 2>/dev/null || true
  echo -e "    ${YELLOW}→ Ensure '$TERMINAL_APP' is allowed${NC}"
  read -p "    Press Enter when done..."

  ok "Permissions configured"
else
  warn "Skipped — remember to grant permissions before first use!"
  info "System Settings → Privacy & Security → Screen Recording / Accessibility / Microphone"
fi

# ── Step 6: Google Meet Audio Setup ──────────────────────────────

echo -e "\n${BLUE}[6/7]${NC} Google Meet audio configuration...\n"

echo "  After joining a Google Meet meeting, configure Chrome's audio:"
echo ""
echo "    1. In Google Meet → Settings → Audio"
echo "       Speaker output: BlackHole 2ch"
echo "       Microphone:     BlackHole 16ch"
echo ""
echo "    This routes:"
echo "       Meeting audio → BlackHole 2ch → CallingClaw (captures)"
echo "       CallingClaw AI → BlackHole 16ch → Meeting mic (speaks)"
echo ""

ok "Audio routing documented"

# ── Step 7: Create Helper Directories ────────────────────────────

echo -e "\n${BLUE}[7/7]${NC} Creating directories...\n"

mkdir -p meeting_notes
mkdir -p data
ok "meeting_notes/ directory created"
ok "data/ directory created"

# ── Done ─────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Setup complete!                                     ║${NC}"
echo -e "${GREEN}║                                                      ║${NC}"
echo -e "${GREEN}║  Start CallingClaw:                                  ║${NC}"
echo -e "${GREEN}║    bun run start                                     ║${NC}"
echo -e "${GREEN}║                                                      ║${NC}"
echo -e "${GREEN}║  Then open: http://localhost:4000                    ║${NC}"
echo -e "${GREEN}║                                                      ║${NC}"
echo -e "${GREEN}║  Docs: docs/deployment-guide.md                     ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
