/**
 * Meeting Prep Recovery — Unit Tests
 *
 * Tests recoverStalePreps() in MeetingScheduler:
 *   - Skip if no preparing sessions
 *   - Recover file found on disk (Case A)
 *   - Skip young sessions (<12 min)
 *   - Regenerate stale sessions (>12 min, Case B)
 *   - Skip if already in _prepInFlight
 *   - Only regenerate one at a time (single-task bridge)
 *
 * Run: bun test test/modules/prep-recovery.test.ts
 */

import { describe, test, expect, beforeEach, mock } from "bun:test";
import { mkdirSync, writeFileSync, rmSync } from "fs";
import { resolve } from "path";
import { homedir } from "os";

// ── Test fixtures ──

const SHARED_DIR = resolve(homedir(), ".callingclaw", "shared");
const SESSIONS_PATH = resolve(SHARED_DIR, "sessions.json");

function writeSessionsJson(sessions: any[]) {
  mkdirSync(SHARED_DIR, { recursive: true });
  writeFileSync(SESSIONS_PATH, JSON.stringify({
    lastUpdated: new Date().toISOString(),
    sharedDir: SHARED_DIR,
    sessions,
  }));
}

function makePrepSession(overrides: Record<string, any> = {}) {
  const meetingId = overrides.meetingId || `cc_test_${Date.now().toString(36)}`;
  return {
    meetingId,
    topic: "Test Meeting",
    status: "preparing",
    startTime: new Date(Date.now() + 30 * 60 * 1000).toISOString(), // 30 min from now
    files: {},
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ...overrides,
  };
}

// ── Mock dependencies ──

class MockCalendar {
  connected = true;
  async listUpcomingEvents() { return []; }
}

class MockOpenClawBridge {
  connected = true;
  async sendTask(t: string) { return "mock"; }
  async sendTaskIsolated(t: string) { return "mock"; }
}

class MockEventBus {
  events: Array<{ event: string; payload: any }> = [];
  emit(event: string, payload: any) {
    this.events.push({ event, payload });
  }
}

class MockMeetingPrepSkill {
  generateCalls: Array<{ topic: string; meetingId?: string }> = [];
  shouldFail = false;

  async generate(topic: string, _ctx?: string, _att?: any[], meetingId?: string) {
    this.generateCalls.push({ topic, meetingId });
    if (this.shouldFail) throw new Error("OpenClaw task timed out");
    // Write the prep file to disk (like the real skill does)
    const filePath = resolve(SHARED_DIR, `${meetingId}_prep.md`);
    writeFileSync(filePath, `# ${topic}\n\nGenerated by test.\n`);
    return {
      topic,
      goal: "test goal",
      generatedAt: Date.now(),
      summary: "test summary",
      keyPoints: ["point 1", "point 2"],
      architectureDecisions: [],
      expectedQuestions: [],
      filePaths: [],
      browserUrls: [],
      folderPaths: [],
      attendees: [],
      liveNotes: [],
    };
  }
}

// ── Import after mocks are ready ──

import { MeetingScheduler } from "../../src/modules/meeting-scheduler";

describe("recoverStalePreps", () => {
  let scheduler: MeetingScheduler;
  let eventBus: MockEventBus;
  let prepSkill: MockMeetingPrepSkill;
  let bridge: MockOpenClawBridge;

  beforeEach(() => {
    eventBus = new MockEventBus();
    prepSkill = new MockMeetingPrepSkill();
    bridge = new MockOpenClawBridge();

    scheduler = new MeetingScheduler({
      calendar: new MockCalendar() as any,
      openclawBridge: bridge as any,
      eventBus: eventBus as any,
      meetingPrepSkill: prepSkill as any,
    });

    // Clean up any leftover test files
    try { rmSync(SESSIONS_PATH); } catch {}
  });

  test("no-op if no preparing sessions", async () => {
    writeSessionsJson([
      makePrepSession({ status: "ready" }),
      makePrepSession({ status: "ended" }),
    ]);

    await scheduler.recoverStalePreps();

    expect(eventBus.events).toHaveLength(0);
    expect(prepSkill.generateCalls).toHaveLength(0);
  });

  test("recovers file already on disk (Case A)", async () => {
    const meetingId = `cc_test_disk_${Date.now().toString(36)}`;
    const prepPath = resolve(SHARED_DIR, `${meetingId}_prep.md`);

    // Write the prep file (simulating OpenClaw wrote it but never called prep-result)
    mkdirSync(SHARED_DIR, { recursive: true });
    writeFileSync(prepPath, `# Test Meeting\n\nThis is a full prep document with enough content to pass the threshold.\n`);

    writeSessionsJson([
      makePrepSession({ meetingId, updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString() }),
    ]);

    await scheduler.recoverStalePreps();

    // Should emit meeting.prep_ready without regenerating
    expect(prepSkill.generateCalls).toHaveLength(0);
    const readyEvents = eventBus.events.filter(e => e.event === "meeting.prep_ready");
    expect(readyEvents).toHaveLength(1);
    expect(readyEvents[0].payload.meetingId).toBe(meetingId);
    expect(readyEvents[0].payload.recovered).toBe(true);

    // Clean up
    try { rmSync(prepPath); } catch {}
  });

  test("skips young session (< 12 min)", async () => {
    const meetingId = `cc_test_young_${Date.now().toString(36)}`;

    // Session updated 3 minutes ago — too young to consider stale
    writeSessionsJson([
      makePrepSession({
        meetingId,
        updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      }),
    ]);

    await scheduler.recoverStalePreps();

    expect(prepSkill.generateCalls).toHaveLength(0);
    expect(eventBus.events).toHaveLength(0);
  });

  test("regenerates stale session (> 12 min, Case B)", async () => {
    const meetingId = `cc_test_stale_${Date.now().toString(36)}`;

    // Session updated 15 minutes ago — stale
    writeSessionsJson([
      makePrepSession({
        meetingId,
        updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      }),
    ]);

    await scheduler.recoverStalePreps();

    // Wait for async generation to complete
    await new Promise(r => setTimeout(r, 100));

    expect(prepSkill.generateCalls).toHaveLength(1);
    expect(prepSkill.generateCalls[0].meetingId).toBe(meetingId);

    // Clean up generated file
    try { rmSync(resolve(SHARED_DIR, `${meetingId}_prep.md`)); } catch {}
  });

  test("skips sessions with startTime > 2h away", async () => {
    writeSessionsJson([
      makePrepSession({
        meetingId: `cc_test_far_${Date.now().toString(36)}`,
        startTime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(), // 5h from now
        updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      }),
    ]);

    await scheduler.recoverStalePreps();

    expect(prepSkill.generateCalls).toHaveLength(0);
  });

  test("skips past meetings", async () => {
    writeSessionsJson([
      makePrepSession({
        meetingId: `cc_test_past_${Date.now().toString(36)}`,
        startTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2h ago
        updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      }),
    ]);

    await scheduler.recoverStalePreps();

    expect(prepSkill.generateCalls).toHaveLength(0);
  });

  test("only regenerates one at a time", async () => {
    // Two stale sessions — should only regenerate the first
    writeSessionsJson([
      makePrepSession({
        meetingId: `cc_test_first_${Date.now().toString(36)}`,
        topic: "First Meeting",
        updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      }),
      makePrepSession({
        meetingId: `cc_test_second_${Date.now().toString(36)}`,
        topic: "Second Meeting",
        updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      }),
    ]);

    await scheduler.recoverStalePreps();
    await new Promise(r => setTimeout(r, 100));

    // Only the first should be regenerated (single-task bridge)
    expect(prepSkill.generateCalls).toHaveLength(1);
    expect(prepSkill.generateCalls[0].topic).toBe("First Meeting");
  });

  test("handles regeneration failure gracefully", async () => {
    const meetingId = `cc_test_fail_${Date.now().toString(36)}`;
    prepSkill.shouldFail = true;

    writeSessionsJson([
      makePrepSession({
        meetingId,
        updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      }),
    ]);

    await scheduler.recoverStalePreps();
    await new Promise(r => setTimeout(r, 100));

    // Should have attempted but no prep_ready event
    expect(prepSkill.generateCalls).toHaveLength(1);
    const readyEvents = eventBus.events.filter(e => e.event === "meeting.prep_ready");
    expect(readyEvents).toHaveLength(0);
  });

  test("skips if OpenClaw bridge disconnected", async () => {
    bridge.connected = false;

    writeSessionsJson([
      makePrepSession({
        meetingId: `cc_test_nobridge_${Date.now().toString(36)}`,
        updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      }),
    ]);

    await scheduler.recoverStalePreps();

    expect(prepSkill.generateCalls).toHaveLength(0);
  });
});
