// CallingClaw 2.0 — Shared Documents HTML Rendering Tests

import { test, expect, describe } from "bun:test";
import { renderToHtml } from "../src/modules/shared-documents";

describe("renderToHtml", () => {
  test("produces valid HTML document with title", () => {
    const html = renderToHtml("# Hello\n\nWorld", "Test Meeting");
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("<title>Test Meeting — CallingClaw</title>");
    expect(html).toContain("<h1>Hello</h1>");
    expect(html).toContain("<p>World</p>");
    expect(html).toContain("</html>");
  });

  test("converts markdown headers to HTML", () => {
    const html = renderToHtml("# H1\n## H2\n### H3", "Headers");
    expect(html).toContain("<h1>H1</h1>");
    expect(html).toContain("<h2>H2</h2>");
    expect(html).toContain("<h3>H3</h3>");
  });

  test("converts markdown formatting", () => {
    const html = renderToHtml("**bold** and *italic* and `code`", "Format");
    expect(html).toContain("<strong>bold</strong>");
    expect(html).toContain("<em>italic</em>");
    expect(html).toContain("<code>code</code>");
  });

  test("converts links", () => {
    const html = renderToHtml("[Google](https://google.com)", "Links");
    expect(html).toContain('<a href="https://google.com">Google</a>');
  });

  test("converts blockquotes", () => {
    const html = renderToHtml("> This is a quote", "Quotes");
    expect(html).toContain("<blockquote>This is a quote</blockquote>");
  });

  test("converts list items", () => {
    const html = renderToHtml("- Item 1\n- Item 2\n1. Ordered", "Lists");
    expect(html).toContain("<li>Item 1</li>");
    expect(html).toContain("<li>Item 2</li>");
    expect(html).toContain("<li>Ordered</li>");
  });

  test("converts horizontal rules", () => {
    const html = renderToHtml("Above\n---\nBelow", "HR");
    expect(html).toContain("<hr>");
  });

  test("handles empty markdown gracefully", () => {
    const html = renderToHtml("", "Empty");
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("<title>Empty — CallingClaw</title>");
  });

  test("handles Chinese content with correct encoding", () => {
    const html = renderToHtml("# 会议准备\n\n## 📌 要点\n\n- 产品方向讨论", "中文测试");
    expect(html).toContain('<meta charset="utf-8">');
    expect(html).toContain("<h1>会议准备</h1>");
    expect(html).toContain("<li>产品方向讨论</li>");
  });

  test("includes inline CSS (self-contained)", () => {
    const html = renderToHtml("# Test", "CSS Check");
    expect(html).toContain("<style>");
    expect(html).toContain("font-family:");
    expect(html).toContain("--accent: #E63946");
    // Should NOT have external stylesheet links
    expect(html).not.toContain('<link rel="stylesheet"');
  });

  test("includes CallingClaw footer", () => {
    const html = renderToHtml("Content", "Footer");
    expect(html).toContain("Generated by CallingClaw × OpenClaw");
  });
});
